name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v3  # Updated to v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Updated to v3
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: bash ./gradlew -PappVerName=${{ env.VERSION }} assembleRelease
      - name: List files in output directory (for debugging)
        run: ls -R app/build/outputs/apk/release/
      - name: Upload APK
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/
